### ISSUE TITLE
Send email on a schedule

### ISSUE THREAD

**Issue by purelogiq** [wchu248/MailerTest#1]
Hi Team,

Your app looks good - from what I see you're sending mail correctly and are just missing the ability to send on a schedule everyday.

To get that second part working:

1. Visit http://github.com/javan/whenever and read the docs for the whenever gem. Install this gem in your project.

2. Create the `schedule.rb` file in the `config` folder as the whenever docs recommend. Your schedule will look something like:

```
every 1.day, :at => "01:10am" do
  runner "UserMailer.send_emails_to_people"
end
```
The `UserMailer.send_emails_to_people` will be a new function in your UserMailer class that loads all Users and decides if it should send an email to each person.

3. Once you deploy the code to your server, do not forget about installing the crontab: run `whenever --update-crontab` in the root of your rails application on the server.

4. Remove your email password from version control: https://github.com/wchu248/MailerTest/blob/2be6f4df3bdef149771406c604c93eb6a8b0d3c9/config/environments/development.rb#L62
You can instead use the system environment on your server to save secrets. An easy way to accomplish this is to use the `dotenv-rails` gem (https://github.com/bkeepers/dotenv). From there you can store secrets in the `.env.production` file on your server and load them in the ruby code with `password = ENV['GMAIL_PASSWORD']`. After setting this up, change your email password.

**Comment by wchu248** [comment]
Hi Israel,

Will the whenever gem work when I run `rails server` and have the server running on my computer locally? I followed the instructions on the documentation for the gem but nothing seems to be working when I run the app on `rails server`.

**Comment by purelogiq** [comment]
@wchu248 The whenever gem is independent of the `rails server` command. There does not need to be any rails application server running for the schedule to run. This is the purpose and beauty of the [crontab](https://www.computerhope.com/unix/ucrontab.htm).

What is required is that on the "server" (by that I mean the actual computer that is running linux/mac os) you've run the `whenever --update-crontab` command. This will update the crontab and the operating system will be responsible for knowing that every X hours it should run Y command (as defined in your `schedule.rb`)

If you want to test that the actual command works as you expected, you can try doing so in `rails console` or on the command line you can run `rails runner 'UserMailer.do_the_emails'`.

If you want to test that the schedule functionality is working, you are free to test this out on your local computer by running the `whenever --update-crontab` command yourself while in the root of your rails app - just remember that once you've moved on from this project you should remove those instructions from your crontab, otherwise your computer will continuously try to email people every x hours while it is on. You should also remove it from your local crontab when you've deployed it properly to your server, otherwise you would have 2 separate computers emailing people.

**Comment by wchu248** [comment]
We got it to work! Qapla!

Thanks for all your work, Israel!
